CREATE TABLE labe2219.UZSAKYMAS (
UzsakymoNR VARCHAR(15) not NULL,
Data TIMESTAMP not NULL,
Adresas VARCHAR(200) not NULL,
Vienetai INTEGER,
PrekesID VARCHAR(15) not NULL REFERENCES labe2219.PREKE(PrekesID),
PilnaKaina FLOAT,
Aprasas VARCHAR(1000),
AtsakingasID VARCHAR(8) not NULL REFERENCES labe2219.DARBUOTOJAS(DarbID),
Uzbaigtas BOOLEAN DEFAULT FALSE,
PRIMARY KEY (UzsakymoNR) )
