CREATE TABLE labe2219.ATASKAITA (
DarbID VARCHAR(8) not NULL REFERENCES labe2219.DARBUOTOJAS(DarbID),
Data DATE not NULL,
Laikas TIME not NULL,
Aprasas VARCHAR(200),
PRIMARY KEY (DarbID, Data) )
