CREATE TABLE labe2219.DARBUOTOJAS (
DarbID VARCHAR(8) not NULL,
Vardas VARCHAR(20) not NULL,
Pavarde VARCHAR(20) not NULL,
Pareigos VARCHAR(50) not NULL,
PRIMARY KEY (DarbID), 
FOREIGN KEY (Pareigos) REFERENCES labe2219.ETATAS ON DELETE RESTRICT
 ) 
